### ISSUE TITLE
call Ruby API in dev

### ISSUE THREAD

**Issue by realdoug** [alanbsmith/react-sinatra-example#2]
Thanks for the starter project, it was very useful.  Just one question, if you are serving the html/js via webpack in dev, how are you calling ruby api methods?  You must be running the sinatra app in a different process on a different port?

if so, curious how you are handling this elegantly in the code?  Thanks

**Comment by alanbsmith** [comment]
Hi! So sorry about the delayed response here. I haven't had much of a need for this project in a while, so I forgot to check up on it.

Yes. I'm running two separate servers (Ruby and webpack-dev-server) locally. Probably the best way to handle this "elegantly" is by using a Procfile and Foreman, which will allow you to run both at once.

```
# Gemfile
...
gem "foreman"
```

```
$ bundle install
$ touch Procfile
```

```
# Procfile
webpack: npm run dev
rails: rails server
```

```
$ foreman start
```

Hope that's helpful if it's still relevant. Apologies again for the delay.
