### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by pvgdevelop** [alanbsmith/react-sinatra-example#3]
Invalid name: "react + sinatra starter"

**Comment by alanbsmith** [comment]
@pav31, so so sorry I've taken so long to respond to this. This issue is now resolved here: https://github.com/alanbsmith/react-sinatra-example/commit/88336536be7fdecd6064bf94aa04b44c8a220448

If you pull down the latest, it should work fine. Thanks for your help!
